/*
Copyright 2022 Contributors to The HwameiStor project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/improved-system/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReplaceDisks implements ReplaceDiskInterface
type FakeReplaceDisks struct {
	Fake *FakeHwameistorV1alpha1
}

var replacedisksResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "replacedisks"}

var replacedisksKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "ReplaceDisk"}

// Get takes name of the replaceDisk, and returns the corresponding replaceDisk object, and an error if there is any.
func (c *FakeReplaceDisks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ReplaceDisk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(replacedisksResource, name), &v1alpha1.ReplaceDisk{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplaceDisk), err
}

// List takes label and field selectors, and returns the list of ReplaceDisks that match those selectors.
func (c *FakeReplaceDisks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReplaceDiskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(replacedisksResource, replacedisksKind, opts), &v1alpha1.ReplaceDiskList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReplaceDiskList{ListMeta: obj.(*v1alpha1.ReplaceDiskList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReplaceDiskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested replaceDisks.
func (c *FakeReplaceDisks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(replacedisksResource, opts))
}

// Create takes the representation of a replaceDisk and creates it.  Returns the server's representation of the replaceDisk, and an error, if there is any.
func (c *FakeReplaceDisks) Create(ctx context.Context, replaceDisk *v1alpha1.ReplaceDisk, opts v1.CreateOptions) (result *v1alpha1.ReplaceDisk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(replacedisksResource, replaceDisk), &v1alpha1.ReplaceDisk{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplaceDisk), err
}

// Update takes the representation of a replaceDisk and updates it. Returns the server's representation of the replaceDisk, and an error, if there is any.
func (c *FakeReplaceDisks) Update(ctx context.Context, replaceDisk *v1alpha1.ReplaceDisk, opts v1.UpdateOptions) (result *v1alpha1.ReplaceDisk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(replacedisksResource, replaceDisk), &v1alpha1.ReplaceDisk{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplaceDisk), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReplaceDisks) UpdateStatus(ctx context.Context, replaceDisk *v1alpha1.ReplaceDisk, opts v1.UpdateOptions) (*v1alpha1.ReplaceDisk, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(replacedisksResource, "status", replaceDisk), &v1alpha1.ReplaceDisk{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplaceDisk), err
}

// Delete takes name of the replaceDisk and deletes it. Returns an error if one occurs.
func (c *FakeReplaceDisks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(replacedisksResource, name), &v1alpha1.ReplaceDisk{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReplaceDisks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(replacedisksResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReplaceDiskList{})
	return err
}

// Patch applies the patch and returns the patched replaceDisk.
func (c *FakeReplaceDisks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ReplaceDisk, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(replacedisksResource, name, pt, data, subresources...), &v1alpha1.ReplaceDisk{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ReplaceDisk), err
}
